### ISSUE TITLE
[wizard] Improve usability of Generic IDE Support option

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-eclipse#119]
![screenshot 96](https://cloud.githubusercontent.com/assets/265597/20172875/19cf2a08-a737-11e6-8b86-8a1cb8ae1d4e.png)

The option "Generic IDE Support" is mandatory for the options "Eclipse Plugin", "IntelliJ IDEA Plugin" and "Web Support". It is not intuitive that this option is the last one. It should be the first option that a user could choose and dependend on the option, the other options should be made selectable.

An option could be to make the different IDE integration options part of a group, as it is with the "Eclipse Plugin" and "Create Feature/Update Site" options. This would also make the error message obsolete, since it is clear that without the Generic IDE option the other options are not valid.

**Comment by svenefftinge** [comment]
There was a longer discussion about this somewhere in bugzilla if I recall correctly.

**Comment by kthoms** [comment]
Could you link that please? If redundant, close this one.

**Comment by svenefftinge** [comment]
I would have done that if I had found it.

**Comment by kthoms** [comment]
I will try to find it tomorrow.

**Comment by kthoms** [comment]
I searched the wizard-related (also closed) bugs, but did not find it either. Thus I would like to discuss this issue here if that's OK.

As said, I suggest that we group specific IDE support options within a generic IDE group. What do you think?

**Comment by dhuebner** [comment]
> The option "Generic IDE Support" is mandatory for the options "Eclipse Plugin", "IntelliJ IDEA Plugin" and "Web Support". It is not intuitive that this option is the last one. It should be the first option that a user could choose and dependend on the option, the other options should be made selectable.

"Generic IDE Support" is more a technical aspect for advance users. Keeping in mind, that wizards are mostly used by people who tries things out or are giving demos (except Xtext consultants), it's better to show the really important thing in top of the wizard page. This things are sorted by importance for a common eclipse user

- I need an eclipse plugin (preselected for eclipse IDE)
- I need an IDEA plugin too (probably not)
- I need web support (probably not)

The two other option like Generic IDE support and tests are considered as 90% needs this and are technical aspects. 

If we compare the default wizard settings with the screen shot above :
![bildschirmfoto 2016-11-15 um 13 41 28](https://cloud.githubusercontent.com/assets/454322/20306217/732fa086-ab39-11e6-8e70-ddf586ba1f4d.png)

I looks like the user goes from top to bottom and tries out the checkboxes. He disables a pre-selected checkbox and gets a feedback message about why it will not work and he also gets a quick-fix for that. IMHO it's a very good UX.

**Comment by kthoms** [comment]
Neither you nor me are these "users" and are no UX experts. I will ask our UX experts to have a look.

**Comment by dhuebner** [comment]
> Neither you nor me are these "users"

That is the point, for the Wizard we need to focus on other users and not the Xtext experts. The result of our discussion a year ago was: The wizard should be as simple as possible, but allow tweaking advance thing.

The first shot of the wizard UI automatically changed and disabled settings depending on last user action and it was terrible.

**Comment by kthoms** [comment]
My feeling is that the page behaves confusing. IMHO it is not simple. 
As said, I'll involve UX experts to get qualified recommendations, or did you involved them in the discussion?

**Comment by SanniSch** [comment]
Because of the discussion of this issue we conducted a Usability Test in which we compared three versions of the wizard: the original one (version 1), the proposal of @kthoms (version 3) and a solution in which "Generic IDE Support" is selected automatically when the three dependent options were selected (version 2). The test results showed that the current wizard supports the users worst. Version 2 supports them best. 

You can find the detailed findings here: http://www.slideshare.net/SandraSchering/usability-test-results-xtext-new-project-wizard

Based on the findings, the wizard should look like the attached mockup. This means the current structure of the dialogue is the same. However, if a user selects "Eclipse Plugin", "IntelliJ..." or "Web Integration", "Generic IDE Support" is selected automatically, the checkbox becomes disabled and a hint is shown. The checkbox becomes active again if none of the three options is selected.

In addition, the results showed that the users did not understand some terms (especially "Generic IDE Support"). Tooltips should be added explaining the meaning of the options.
![version2_automatic-selection](https://cloud.githubusercontent.com/assets/16920235/21315516/ded13060-c5fc-11e6-9131-4e54e54f28cc.PNG)

**Comment by kthoms** [comment]
Fixed via 96ed73c

**Comment by kthoms** [comment]
There is a similar situation with the dependency between the P2 and Feature project. The update site project requires the feature project. Therefore it should the same that the feature project is automatically selected and disabled when the update site project is selected and the user gets a message.
Further, it does not make sense to leave the feature and update site selected when Eclipse plug-in is deselected. The user could assume that the projects are still produced since the boxes are checked. The options should be automatically deselected. A further information in the status widget should not be necessary in that case.
