### ISSUE TITLE
Make usage of internal JDT API compatible to latest changes

### ISSUE THREAD

**Issue by szarnekow** [eclipse/xtext-eclipse#1450]
In https://github.com/eclipse/xtext-eclipse/blob/106b597f755f63be3ea81c88865ce38c0b4cf343/org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/ui/notification/JavaBuilderState.java#L226 we read the references field from JDTs internal State which is about to be changed via https://git.eclipse.org/r/#/c/162792/

**Comment by iloveeclipse** [comment]
@cdietrich : I must know which effect this may have on our product, because I want to pull it into our custom Eclipse build. 
Could you please check if we are affected or not?
I see where the code is used (com.advantest.itee.tpl.ui.internal.BuilderDeltaConverter2.convertChangedCompilationUnit(IJavaElementDelta, List<Delta>)), but it doesn't say me much.

Obviously the logic in org.eclipse.xtext.common.types.ui.notification.DeltaConverter.convertChangedTypeAndChildren(List<Delta>, TypeNames, IType, URI) and org.eclipse.xtext.common.types.ui.notification.DeltaConverter.convertRemovedTypes(TypeNames, List<Delta>) will be affected, so some delta state will be different.

**Comment by cdietrich** [comment]
yes this will break our code
(correct reaction to changes/removals of TM-Java Files in DSL files)

**Comment by cdietrich** [comment]
unfortunately patching is hard as we use statics
