### ISSUE TITLE
Modify API of TemplateWizards and WizardPage

### ISSUE THREAD

**Issue by hannesN** [eclipse/xtext-eclipse#1610]
In a project we needed to override some methods or set initial values in the TemplateWizard. Sadly most of the methods in the `TemplateNewFileWizard` and `NewFileWizardPrimaryPage` are private. So I suggest making them at least protected.

`TemplateNewFileWizard`
fields should get a getter, so we are able to instantiate our own main page based on the `NewFileWizardPrimaryPage`

Also: We should inject a GeneratorProvider instead of:
`WorkspaceFileGenerator fileGenerator = new WorkspaceFileGenerator();`

`NewFileWizardPrimaryPage`
We should create protected methods: `initFolderText` and `initFileText`.
Also make `validate` and `[set|get]TemplateInfo`protected, so we can access it outside the package.
Any package private method should be at least protected.

I would implement the changes and create an PR if you accept my suggestions.

**Comment by cdietrich** [comment]
@ArneDeutsch what do you think?

**Comment by miklossy** [comment]
I have also encountered this problem while implementing the [DotProjectTemplateProviderTest](https://github.com/eclipse/gef/blob/master/org.eclipse.gef.dot.tests/src/org/eclipse/gef/dot/tests/DotProjectTemplateProviderTest.xtend) and the [DotFileTemplateProviderTest](DotFileTemplateProviderTest) test cases.

Currently, I am using reflections to access the values of these private fields, such as [setProjectInfo](https://github.com/eclipse/gef/blob/3138407e71f800d8c5bf7fca0fd217df9c03d154/org.eclipse.gef.dot.tests/src/org/eclipse/gef/dot/tests/DotProjectTemplateProviderTest.xtend#L125-L129) and [setTemplateInfo](https://github.com/eclipse/gef/blob/3138407e71f800d8c5bf7fca0fd217df9c03d154/org.eclipse.gef.dot.tests/src/org/eclipse/gef/dot/tests/DotFileTemplateProviderTest.xtend#L221-L225).

I think it would be a good idea to open up these classes as little bit as @hannesN suggested. Since this API is still marked as `@Beta`, we can extend it with no risk.

**Comment by cdietrich** [comment]
ping @ArneDeutsch @szarnekow

**Comment by szarnekow** [comment]
Please move this forward. I'm all in favour of making this feature easier to consume and customize.

**Comment by miklossy** [comment]
> I would implement the changes and create an PR if you accept my suggestions.

@hannesN How is the progress here?

**Comment by hannesN** [comment]
Sorry didn't had the time yet.

**Comment by ArneDeutsch** [comment]
I implemented the proposed changes as closely as I can. @hannesN please review if the changes in https://github.com/eclipse/xtext-eclipse/commit/646099973690997c50016a3fa2a5d4e1efaee1cc fullfill your needs.
