### ISSUE TITLE
Support more fine granular "needsRebuild" on generation to different projects

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#1820]
Support more fine granular "needsRebuild" on generation to different projects
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=579082

**Comment by cdietrich** [comment]
@szarnekow do you see any way to achieve this without breaking api
if we replace / add to 

IBuildContext.needsRebuild a IBuildContext.needsRebuild(IProject)
and people subclass that, it wont be called anymore

**Comment by szarnekow** [comment]
I'd probably go for the invenient but so far reliable approach that checks the implementation class. If the type of the BuildContext is the Xtext default type, we don't call needsRebuild. If it is not and the actual type has an overridden needsRebuild, we call it from needsRebuild(IProject)

**Comment by cdietrich** [comment]
yes but i have no clue how jörg manages to write to other projects without subclassing.

**Comment by szarnekow** [comment]
I think that's supported by if one uses custom generator outlets, e.g. if `org.eclipse.xtext.generator.OutputConfiguration.getOutputDirectory()` returns something `../../projectName/...`

**Comment by cdietrich** [comment]
yes but this will only work if projects are contained in the ws and not imported only

**Comment by szarnekow** [comment]
I don't think so - the path resolution is relative the ws root, isn't it?

**Comment by cdietrich** [comment]
yes. thus i really wonder how jörg does it

**Comment by cdietrich** [comment]
@ Jörg the change that we now do request rebuild on affected projects

**Comment by iloveeclipse** [comment]
@cdietrich : I think Jörg is not subscribed to this ticket :-)

**Comment by cdietrich** [comment]
yes i dont know if he has an github account at all

**Comment by szarnekow** [comment]
Pinging @jukzi: Can you please take a look at this conversation, Jörg?

**Comment by jukzi** [comment]
thanks, i can probably test tomorrow.

**Comment by jukzi** [comment]
We have serious issues with the current xtext builds:

At a first glance after clean build many project with Java Problem:
"The project cannot be built until its prerequisite XXX is built. Cleaning and building all projects is recommended"

I debugged and found why: we have set manual build order in preferences. The build order was wrong. Former Xtext did cure that wrong wrong build order by requesting rebuild.
Well, after fixing the build order now i know there is no cycle in our projects: we would not need any rebuilds of projects that already have been build.
Testing xtext then again with a build order that should not need any rebuilds i see it compiles. But it does a costly but unneeded second round. That is caused by files created within the current build project (which is the very intention of xtext). xtext then calls requestProjectsRebuild(project) with project ==currentProject. 

This could be solved by:

```
diff --git a/org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/BuildContext.java b/org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/BuildContext.java
index 0cdae74..f717c42 100644
--- a/org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/BuildContext.java
+++ b/org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/BuildContext.java
@@ -58,13 +58,17 @@
 	@Deprecated
 	@Override
 	public void needRebuild() {
-		builder.triggerRequestProjectRebuild();
+		builder.needRebuild(); //backward compatibility
 	}
 	
 	@Override
 	public void needRebuild(IProject project) {
 		if (BuildContext.class == getClass()) {
-			builder.triggerRequestProjectsRebuild(project);
+			if (getBuiltProject().equals(project)) {
+				builder.triggerRequestProjectRebuild();				
+			} else  {
+				builder.triggerRequestProjectsRebuild(project);
+			}
 		} else {
 			needRebuild();
 		}
```

Then there is also a much more serious problem: We use eclipse.tea for building the workspace. And when using that xtext now permanently requests rebuilds from org.eclipse.xtext.builder.impl.XtextBuilder.pollQueuedBuildData(). I will continue to investigate why - but i can already say it feels just wrong that you request rebuild of only the current project when there is a delta in another project detected. "for(IProject project: interestingProjects) {"

**Comment by cdietrich** [comment]
The first change I don’t understand can you explain

@iloveeclipse does the rebuild with project build called on current project behave differently as called without project

**Comment by cdietrich** [comment]
@jukzi it would really help to know how you generate to different projects

**Comment by cdietrich** [comment]
@jukzi it would really help to know how you generate to different projects

**Comment by jukzi** [comment]
There is probably not a single kind of how to create files. But i can give an example i just see - this makes xtext endless requesting rebuilds in eclipse.tea:

 new java.io.File.File(File, String) 
 //... write...
  IProject.refreshLocal(IResource.DEPTH_INFINITE, null);

The file is created in another project - and  in this case not even by xtext. Still xtext detects that delta in
org.eclipse.xtext.builder.impl.javasupport.JdtQueuedBuildData.doNeedRebuild(JavaBuilderState, Procedure1<? super UnconfirmedStructuralChangesDelta>)
but since its in another project it is pointless to (endlessly) request rebuild of the current Project only.

**Comment by cdietrich** [comment]
but this wont cause the buildcontext needsrebuild as you bypass xtext api completely

**Comment by jukzi** [comment]
> but this wont cause the buildcontext needsrebuild as you bypass xtext api completely

sure it does not use xtext API. but xtext DOES SEE the delta in JdtQueuedBuildData.doNeedRebuild()
if xtext sees a delta in another project it has to call doNeedRebuild(project) . JdtQueuedBuildData.doNeedRebuild should probably return a set of projects it wants to rebuild. its not just a binary decision rebuild or not with the new api.

**Comment by cdietrich** [comment]
i fear we need to wait until @szarnekow has some time to help me to understand JdtQueuedBuildData and the usecases

**Comment by jukzi** [comment]
> The first change I don’t understand can you explain

what exactly is unclear? see javdoc of org.eclipse.core.resources.IncrementalProjectBuilder.requestProjectsRebuild(Collection<IProject>):

"if the given collection contains the current project (that is currently built with current builder), the current project will be not rebuilt immediately"

**Comment by cdietrich** [comment]
wip branch is https://github.com/eclipse/xtext-eclipse/tree/cd_xtext_eclipse_issue1820_b

**Comment by cdietrich** [comment]
update site with your patch proposal https://ci.eclipse.org/xtext/job/xtext-umbrella/job/cd_xtext_eclipse_issue1820_b/lastSuccessfulBuild/artifact/build/p2-repository/

**Comment by cdietrich** [comment]
@szarnekow what do you think about the change in
https://github.com/eclipse/xtext-eclipse/tree/cd_xtext_eclipse_issue1820_c

**Comment by cdietrich** [comment]
another version available now.

**Comment by cdietrich** [comment]
TODO think about better treatment of unconfirmed deltas
https://github.com/eclipse/xtext-eclipse/compare/cd_xtext_eclipse_issue1820_c

**Comment by szarnekow** [comment]
> TODO think about better treatment of unconfirmed deltas https://github.com/eclipse/xtext-eclipse/compare/cd_xtext_eclipse_issue1820_c

It would be great if the entire overhead would be optional. Environments without a language that needs Java types should not "suffer" from the processing of deltas and internal Java compiler state.

**Comment by jukzi** [comment]
Could you please merge https://github.com/eclipse/xtext-eclipse/compare/cd_xtext_eclipse_issue1820_c as is? We need it and you could still do improvements afterwards.

**Comment by cdietrich** [comment]
Sebastian says it should not be merged ?

**Comment by cdietrich** [comment]
Cc @szarnekow

**Comment by szarnekow** [comment]
> Sebastian says it should not be merged ?

I think https://github.com/eclipse/xtext-eclipse/compare/cd_xtext_eclipse_issue1820_c looks fine for now. It's certainly an improvement. Nevertheless JdtQueuedBuildData and friends seem to require an overhaul since they've caused to much trouble in the past, especially for languages that do *not* depend on the Xtext common.types.

**Comment by cdietrich** [comment]
@jukzi nightly should contain it torrow

**Comment by jukzi** [comment]
thanks. works for me now.

**Comment by szarnekow** [comment]
> thanks. works for me now.

Excellent. Thank you for reporting back, Jörg.

@cdietrich Nice piece of work that you pulled off here. I really like the more fine-grained approach towards requesting builds from the code gen.

**Comment by cdietrich** [comment]
@szarnekow are we fine now for now or should we create a follow up task?

**Comment by cdietrich** [comment]
ping @szarnekow
