### ISSUE TITLE
Highlighting is done twice

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#347]
Having a XtextEditor opened, Semantic highlighting is done twice.
once via `org.eclipse.xtext.ui.editor.syntaxcoloring.HighlightingReconciler.refresh()`  called via `org.eclipse.xtext.ui.editor.XtextEditor.installHighlightingHelper()` and once via `org.eclipse.xtext.ui.editor.XtextEditor.forceReconcile()` 

@spoenemann do you remember why you introduced the second one being called from `org.eclipse.xtext.ui.editor.XtextEditor.createPartControl(Composite)`

**Comment by spoenemann** [comment]
See https://github.com/eclipse/xtext-eclipse/commit/d4fe755d6dd211ce0ca0d498d3f9e5913d4659e6:

> added forceReconcile() to XtextEditor.createPartControl(..) to avoid conflicts during initialization of the outline view

**Comment by cdietrich** [comment]
yes but this tells me and sebastian zero. )=> what kind are these conflicts of

**Comment by spoenemann** [comment]
Don't remember...

**Comment by cdietrich** [comment]
cc @svenefftinge any thoughts?

**Comment by svenefftinge** [comment]
Sorry, no idea.

**Comment by ArneDeutsch** [comment]
Experimented with highlighting while open/close outline view, setting breakpoints etc. Can not find any side effect when removing the "forceReconcile()" call. I guess the original bug 454227 was fixed by the other changes inside https://github.com/eclipse/xtext-eclipse/commit/d4fe755d6dd211ce0ca0d498d3f9e5913d4659e6 and the added "forceReconcile()" was a mistake. After removing the call no duplicate highlighting happens any more. This should improve performance for large files or files with expensive semantic highlighting quite a lot.

**Comment by dhuebner** [comment]
@ArneDeutsch  After switching to 2.14 I'm facing an issue with missing Semantic Highlighting in a custom DSL Editor and synchronized custom View. What is the strategy for users to easily fix the misbehavior on the synchronized View side (similar to outline view)

**Comment by dhuebner** [comment]
I will answer my question. The first thing to do is, to scan the code for `document.priorityReadOnly` calls. 😑

**Comment by dhuebner** [comment]
@ArneDeutsch The problem was that the initial semantic highlighting stopped working after updating to 2.14. The reason was a `priorityReadOnly` call that prevented the semantic highlighter to finish the job. 
Removing unnecessary forceReconcile is fine to me.  Now, missing initial highlighting is a good indicator for bad implementation around the document access API.

**Comment by cdietrich** [comment]
so the problem is that you in your view executed a priorty readonly that cancelled the highlighting?

**Comment by dhuebner** [comment]
Yes
