### ISSUE TITLE
StratumBreakpointAdapterFactory is registered for XtextEditor

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#463]
StratumBreakpointAdapterFactory is registered as adapter factory for xtext editor
for all xbase languages
imho it should be registered for a language specific subclass of XtextEditor

**Comment by cdietrich** [comment]
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=471773 as well

**Comment by FStolte** [comment]
I was able to reproduce the bug that should be removed by this enhancement in the following way:

- I created two copies of the class `StratumBreakpointAdapterFactory`
- I configured them as factories for the `org.eclipse.debug.ui.actions.IToggleBreakpointsTarget` adapter type, one for the Xtend language and the other for the domainmodel language:

```
org.eclipse.xtext.example.domainmodel.ui\plugin.xml:
<extension point="org.eclipse.core.runtime.adapters">
    <factory class="org.eclipse.xtext.example.domainmodel.ui.DomainmodelExecutableExtensionFactory:org.eclipse.xtext.builder.smap.StratumBreakpointAdapterFactory2"
        adaptableType="org.eclipse.xtext.ui.editor.XtextEditor">
        <adapter type="org.eclipse.debug.ui.actions.IToggleBreakpointsTarget"/>
    </factory> 
</extension>

org.eclipse.xtend.ide\plugin.xml:
<extension  point="org.eclipse.core.runtime.adapters">
    <factory class="org.eclipse.xtend.ide.XtendExecutableExtensionFactory:org.eclipse.xtext.builder.smap.StratumBreakpointAdapterFactory3"
        adaptableType="org.eclipse.xtext.ui.editor.XtextEditor">
        <adapter type="org.eclipse.debug.ui.actions.IToggleBreakpointsTarget"/>
    </factory> 
</extension>
```

- I started a runtime eclipse and created an .xtend file and a .dmodel file

Now, when opening either of the files, only `StratumBreakpointAdapterFactory3` is called, despite being only configured for one of the two languages.

**Comment by kthoms** [comment]
Test languages have to be updated as well

**Comment by FStolte** [comment]
While updating the test languages I found another problem. In the current state, when generating code for a language that does not use `StandardLanguage` and does not explicitly use the EditorFragment, there is a compilation error in the generated code. This is due to a guice binding that is happening in the `ImplicitFragment`:
```
if (isGenerateStub) {
    bindingFactory.addTypeToType(grammar.eclipsePluginDefaultEditor, grammar.eclipsePluginEditor)
} else if (inheritsXbase(grammar)) {
    bindingFactory.addTypeToType(grammar.eclipsePluginDefaultEditor, grammar.eclipsePluginXbaseEditor)
}
```

This could be solved by putting the binding of the generated editor into the editor fragment; however, for languages that inherit from Xbase, the binding of the Xbase editor to the Xtext editor should happen even if the EditorFragment is not used. If we set the binding to the Xbase editor in the implicit fragment, then we cannot reset it in the editor fragment since the `BindingFactory` only supports adding bindings and throws an exception when trying to create a duplicate binding.

**Comment by FStolte** [comment]
Karsten and I already discussed one possible fix. It still has a flaw, but seems fair enough if noone else can come up with a nicer solution.

We can move the binding for the Xbase editor into the Xbase generator fragment and ensure in the StandardLanguage that this fragment is executed after the editor fragment. Then, we can try to set the binding for the Xbase editor and if it fails, we know that the editor fragment already has set the binding.

With this solution, there is still the problem that a language that does not use StandardLanguage might execute the fragments in the wrong order, in which case an exception is thrown. Nevertheless, we can provide an exception message that explains how to fix this (probably rarely occurring) problem.

By the way: there are several bindings done in the ImplicitFragment that are only relevant to Xbase languages. Is there a reason why these are not done in the Xbase generator fragment?
```
if (inheritsXbase(grammar)) {
    bindingFactory.addTypeToType('org.eclipse.xtext.ui.editor.model.XtextDocumentProvider'.typeRef,
        'org.eclipse.xtext.xbase.ui.editor.XbaseDocumentProvider'.typeRef)
        .addTypeToType('org.eclipse.xtext.ui.generator.trace.OpenGeneratedFileHandler'.typeRef,
        'org.eclipse.xtext.xbase.ui.generator.trace.XbaseOpenGeneratedFileHandler'.typeRef)
}
```

**Comment by kthoms** [comment]
@cdietrich @szarnekow wdyt?

**Comment by cdietrich** [comment]
what do you mean by "fail"

**Comment by kthoms** [comment]
The problem is that it is not allowed to add a binding twice, see BindingFactory#addTypeToType and #add l.140.
The editor binding should be provided by the EditorFragment2, not by the ImplicitFragment. But Xbase would have to provide its binding for the XbaseEditor even without the EditorFragment, since there are Xbase based languages that don't use StandardLanguage and thus not the EditorFragment. If the binding is only provided by the EditorFragment, then those languages would not have a binding.
So the idea is that XbaseGeneratorFragment2 would do this binding if the EditorFragment2 did not do this before. For this, EditorFragment2 has to be in StandardLanguage before XbaseGeneratorFragment2 and the latter should expect an exception when trying to do the binding.

I don't think we have such a situation before.

> is adding no editorfragment not the same as using generateStub=false

No. The problem is the Guice binding. The ImplicitFragment does not know whether the editor fragment is present or not. If we move all the registration things to the fragment, then this would can have that effect.

**Comment by cdietrich** [comment]
no my initial question was (2 weeks ago) why not everything in implicit fragment

**Comment by kthoms** [comment]
Main reason for that was that ImplicitFragment did not generate classes so far, and this is typically done by other fragments.

Granted, that fragment does mostly configure editor related stuff. On the other side: Is that correct here? It is for all languages indepently of whether they have an Eclipse editor or not.

**Comment by cdietrich** [comment]
yes but the binding has a guard as well same for plugin.xml
@szarnekow what do you think?

**Comment by kthoms** [comment]
As a result of discussion with @cdietrich & @szarnekow we think that it would be better to limit specific editors to Xbase languages only. Thus the editor shall be generated by XbaseGeneratorFragment2, the binding done there also and the EditorFragment2 deleted.

Please adjust the generator and regenerate the languages.

**Comment by FStolte** [comment]
Generation of Editor bindings is faulty, causing the issues in [eclipse/xtext-xtend#333] and [eclipse/xtext-xtend#334].
I already fixed the bug and I'll do a pull request as soon as I regenerated the affected languages.

**Comment by cdietrich** [comment]
@kthoms do we have anything left for this? if yes please provide prs

**Comment by kthoms** [comment]
Looks as if this is complete now.
