### ISSUE TITLE
[quickfix] Add quickfix for create action

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-eclipse#51]
A rule 
   `Foo: 'id' (name=ID)?;Foo: 'id' (name=ID)?;`
produces the warning 
   `The rule 'Foo' may be consumed without object instantiation.
   Add an action to ensure object creation, e.g. '{Foo}'.`

Adding this action could be provided by a quickfix.

**Comment by meysholdt** [comment]
What would be the proposed strategy to decide where and what actions to insert? Cann all cases be handled? 

Example:

  Rule:
      name=ID? | {Other} 'other';

**Comment by kthoms** [comment]
Your example is a good example for that not all cases can be handled correctly. But is this the intention of a quickfix? It is just a proposal for what you could do to correct the situation. It is not said that is the perfect solution, this is true also for other quick fixes. And as the warning already proposes is that you could add a create action for the rule that you just created.

Many rules that I have seen place the create action at the beginning, so that is at least a valid fix. If you have to decide more decent where the create action is to be placed and what kind of object should be created, you would not want to use the quickfix anyway. But newbies might appreciate such a fix that does what the warning message proposes.

I think the quickfix could be labeled "Insert create action `'{Foo}'` on rule entry.".

**Comment by meysholdt** [comment]
I think a quickfix should only be available for scenarios that it can fix reliably. A quickfix that turns a warning into an error makes the tool look broken.

And yes, there are scenarios where a simple quickfix can work:

`R1: 'X'?;`  --> `R1: {R1} 'X'?;`
`R2: name=ID?;`  --> `R2: {R2} 'name=ID'?;`

For others, "place the create action at the beginning", leads to errors:

`R3: ("true" | {False} "false")` --> `R3: {R3} ("true" | {False} "false")`

The latter is erroneous because current EObject may only be instantiated once.

So a prerequisite for this quickfix implementation would be that it does not offer itself for scenarios it can't solve.

**Comment by kthoms** [comment]
Agreed.

**Comment by ArneDeutsch** [comment]
Added implementation that can handle all cases together with test cases.

**Comment by kthoms** [comment]
Please describe the feature also in the release notes:
https://github.com/eclipse/xtext/blob/website-master/xtext-website/_posts/releasenotes/version-2-14-0.md

**Comment by szarnekow** [comment]
Im asking to reopen this bug and address the issues from the review. Also Moritz mentioned a few things in this discussion.

**Comment by ArneDeutsch** [comment]
The review findings were addressed and I executed the tests again on master. Looks all good to me. Propose to close this issue.
