### ISSUE TITLE
New Copy Qualified Name Service might break existing impls

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-eclipse#517]
please make sure the new service still works with customizations of the old interface.

proposal by @szarnekow 

- add a binding from new interface to old interface to defaultuimodule

@kthoms @ArneDeutsch can you please evaluate

**Comment by ArneDeutsch** [comment]
The issue as I underastand it:
- A user might @Inject the old (deprecated) interface
- He might expect to get an extension of XbaseCopyQualifiedNameService (probably XtendCopyQualifiedNameService)
- With current implementation this is not possible because XbaseCopyQualifiedNameService does not implent the old interface any more

Solution:
- XbaseCopyQualifiedNameService should extend deprecated DefaultCopyQualifiedNameService (and hance indirectly new DefaultCopyQualifiedNameService)
- Bind both (the new and the old interface) the the same implementation

**Comment by ArneDeutsch** [comment]
XtendCopyQualifiedNameServiceTest is quite handy to test that the binding works as expected. One can use the old and the new implementation for the member "copyQualifiedNameService" and it continues to succeed.

**Comment by cdietrich** [comment]
no i see the same problem in non xbase as well.
if user has 

MyCustomFQNSerive bound it will no longer be used by the new solution

@szarnekow @kthoms can you please assist arne cause i am busy today

**Comment by cdietrich** [comment]
@szarnekow @ArneDeutsch @kthoms do i see it correct that CopyQualifiedNameService was non api so far? so does that mean we dont have a problem here? or should we even remove the old interfaces all together? or do we keep them for binary compatibility?

**Comment by cdietrich** [comment]
But if its internal how could this ever work?

```
<handler
			class="org.xtext.example.mydsl.ui.MyDslExecutableExtensionFactory:org.eclipse.xtext.ui.editor.copyqualifiedname.EditorCopyQualifiedNameHandler"
			commandId="org.eclipse.xtext.ui.editor.copyqualifiedname.EditorCopyQualifiedName">
			<activeWhen>
				<reference definitionId="org.xtext.example.mydsl.MyDsl.Editor.opened" />
			</activeWhen>
		</handler>
``` 

shitty pde tooling?

**Comment by ArneDeutsch** [comment]
The package was exported but hidden from all except for "org.eclipse.xtenbd.ide" and "org.eclipse.xtext.xbase.ui". Hance everybody can use it, but will get a warning when doing so.
