### ISSUE TITLE
SDK feature is missing new testing bundles

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-eclipse#58]
The new `org.eclipse.xtext.testing` bundle has to be added to the Xtext SDK feature. Further, the bundle `org.eclipse.xtext.xbase.testing` must be added.

**Comment by meysholdt** [comment]
agreed, even though `xbase.junit` is in feature `org.eclipse.xtext.xbase`, so your proposal effectively moves the test helpers to the SDK feature. 

Having the test helpers in SDK features is a good thing IMHO since it allows to use the non-sdk-feautres for feature-based product definitions. In those product definitions one usually doesn't want to have the test helpers included.

**Comment by kthoms** [comment]
https://github.com/eclipse/xtext-eclipse/pull/59

**Comment by meysholdt** [comment]
merged. thx!
