### ISSUE TITLE
Mark test source folders

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-eclipse#677]
JDT has a new feature in Photon that allows source folders to be marked to contain test sources. Xtext should set this flag when running on Photon. As an additional requirement test source folders must have a separate output folder. Consider also different source layouts!

![screenshot 107](https://user-images.githubusercontent.com/265597/40161693-f07d1726-59b1-11e8-9711-5625cbf195d0.png)

This will be configured in `.classpath`then:
```
	<classpathentry kind="src" output="bin/test" path="src/test/java">
		<attributes>
			<attribute name="test" value="true"/>
			<attribute name="gradle_scope" value="test"/>
			<attribute name="gradle_used_by_scope" value="test"/>
		</attributes>
	</classpathentry>
```

**Comment by cdietrich** [comment]
should set the test scope for the junit 5 lib too
```
<classpathentry kind="con" path="org.eclipse.jdt.junit.JUNIT_CONTAINER/5">
		<attributes>
			<attribute name="test" value="true"/>
		</attributes>
	</classpathentry>
```

**Comment by cdietrich** [comment]
+ we need separate output folders

**Comment by ArneDeutsch** [comment]
I have implemented with the comits above. It works well for both lsource layout styles. Output folders as well as test folder marking are supported.
But to make it in a nice way I have introduced a breaking API change: https://github.com/eclipse/xtext-core/commit/feda0f056f5221683981a7d233b97d32760aadc2#diff-ad6b8504b80690875c0841958f4ab215
For me this looks acceptable, as this API is the Xtext Wizard and it seems unlikely for me that users build much on top of this code. In addition a fix would be not so hard on users side. Do you think this is acceptable? The option would be to NOT break the API, but in this case the resulting API would not be nice, because "sourceFolder" and information of "outputFolder-per-sourceFolder" and information if a source folder is a test folder would be specified seperately. Opinions?

**Comment by ArneDeutsch** [comment]
Done.

**Comment by ArneDeutsch** [comment]
Issues on Jenkins. Will handle.
